### ISSUE TITLE
Deposit Storage

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#11]
After i upgrade the original map for the new one, the itens from deposit are gone.

I revert the map update and items are back. 

Do you know if is necessary sql update? cuz the items still on database but idk if the storage key change with the map for some reason.

**Comment by gordonbay** [comment]
Wasn't able to identify any problem with deposit storage, probably your problem happened after 0.0.4 update cause the map changes.

**Comment by gexarthas** [comment]
I figured out what happened :

Mitsuig map Darashia deposit is represented by id 10.

Your Map i dont know why is 0.

Not really a bug but if someday someone need migrate for this datapack the may know this issue can happen, the items will still there but maybe in a diferente place where they put.
