### ISSUE TITLE
Reward Chest

### ISSUE THREAD

**Issue by ramses82** [gordonbay/capernia-ots-datapack#12]
Reward chest gives the loot that you get on monster when kill, (Ghazbaran) when you kill him you get his loot but then at reward chest you get it again

32378, 32240, 7.

**Comment by gordonbay** [comment]
I wasn't able to replicate any problem regarding `reward container` or `bosses loot` it is working just like it should be. However the `reward container` only be avaliable on Adventurers' Guild and i ll fix that.

**Comment by gordonbay** [comment]
As there was no response i ll close it.
