### ISSUE TITLE
Ferumbras Ascendant Quest Treasure Chest Clonation Bug

### ISSUE THREAD

**Issue by ramses82** [gordonbay/capernia-ots-datapack#13]
you can take the chest with you (bp) and If you put stuff on it  (1kk) , make a new account  use the chest you get the stuff  x2

- If you put the  something sparkling on it Fixed

**Comment by gordonbay** [comment]
I have been able to replicate this problem and will fix it. Keep reporting problems and test again after the update. Next time [read the issues section rules](https://github.com/gordonbay/capernia-ots-datapack/wiki/Issues), you should have provided the exact location of the problem **33388, 31413, 14**.
