### ISSUE TITLE
Bog Raider's Edron - Broken Map

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#14]
Some bug's on respaw:
![print1](https://cloud.githubusercontent.com/assets/11077805/15265405/5dce9106-1959-11e6-9594-57399412a365.png)
![print2](https://cloud.githubusercontent.com/assets/11077805/15265411/64590254-1959-11e6-97b4-343b2ce72650.png)

This one u cant even use the rope.
![print3](https://cloud.githubusercontent.com/assets/11077805/15265413/6cd4d3fe-1959-11e6-86af-ec90f0ca72fe.png)

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon.
