### ISSUE TITLE
Yalahar Access

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#16]
It's not a really bug but like here: Port Hope boat
![print6](https://cloud.githubusercontent.com/assets/11077805/15265450/25bdc272-195a-11e6-8768-8a2a6b326a46.png)

The right thing for charles and others isn't chek if did do I start the Way of Yalahar quest?

Other example is like that the teleports are right but the gates are gone xD

![print5](https://cloud.githubusercontent.com/assets/11077805/15265448/1eb0eae0-195a-11e6-898f-b10512bd2fe4.png)

**Comment by gordonbay** [comment]
Gates will fixed on the next update. About Charles i can't say there is a bug neither you so i ll just close this topic.

**Comment by gexarthas** [comment]
@About Charles e others Captain who travel to yalahar. 
Can you teach me how do I check it like you did with Chemar and farmine? To make mandadory players finish Way of Yalahar first before been able to travel there?

**Comment by gordonbay** [comment]
You need check file npcname.lua and search for conditionals. I changed Captain max and now it checks way to yalahar quest to travel you.

**Comment by gexarthas** [comment]
Thx u are the best. If i can help out somehow let me know

**Comment by RafaelPereiraa** [comment]
The real situation is that any of the captains that can send you to yalahar needs a fix on quest check.
