### ISSUE TITLE
Oramond Monster Corps

### ISSUE THREAD

**Issue by ramses82** [gordonbay/capernia-ots-datapack#17]
Oramond Monsters have wrong Ids and they turn into other items for example mooh'tah warrior turns to this 
Location 33549, 32012, 7.
-minotaur amazon
- moohtant
- mooh'tah warrior
- worm priestess
- blood beast
-minotaur hunter
-rustheap golem
- metal gargoyle
-execowtioner
- glooth blob
- rot elemental 

![captura](https://cloud.githubusercontent.com/assets/18301510/15265725/bfcb3158-1949-11e6-8ec2-a85001a70dc7.JPG)
![captura2](https://cloud.githubusercontent.com/assets/18301510/15265726/bfce45dc-1949-11e6-9511-e159c19f0697.JPG)

- Fix Changing to Correct Corpes Ids

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon. Capernia 2 Staff
