### ISSUE TITLE
Check "Mitsuig" datapack claim

### ISSUE THREAD

**Issue by gordonbay** [gordonbay/capernia-ots-datapack#18]
[This guy ](http://www.tibiaking.com/forum/topic/36403-global-full-tibiaking-10911092-tfs-12-full-oramond-cast-system-lions-rock-reward-system-equip-hotkey-new-items-news-monster-new-areas-krailos-asura-medusa-town-etc-eventos-sem-missao-v20/) claims to have done some improvements to his build, we need to check that and if is true scrap what we need to improve our code.

While this matter goes i made a change on readme:
![Aware of this but nothing done yet!](https://img.shields.io/badge/aware-0%25-red.svg)
please keep it updated.

**Comment by gordonbay** [comment]
I have finished scraping all Mitsuig datapack and can be said that most of it is a copy of the latest version of [ORTS Project](https://github.com/orts/server). Somehow the map file has been vastly modified to avoid default quest flow and bypass some mission requiriments. Although the autor tag its release as been 10.91/10.92 it misses several new resources present on this versions like the new potions. And talking about resources, several scripts have been received modifications and translation to PT-BR without following any criterea. The community has been able to find several segurity related issues and they are still on the main release making the Mitsuig datapack unsafe.
I don't think we should follow this project, first because it's author follows no criterea on its development, second, there are several security related issues that I and the community found.

![](https://img.shields.io/badge/build-unsafe-red.svg)    ![](https://img.shields.io/badge/action-don't follow-red.svg)

**Comment by malandriso** [comment]
Security issues such as...? Would you be kind enough to link me to these findings?
