### ISSUE TITLE
Exori Gran Con - Paladin Spell

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#19]
There is something wrong with the exori gran con spell the damage is too high i did hits over 543+

This char is a paladin lvl 100 with 86 dist
![print2](https://cloud.githubusercontent.com/assets/11077805/15345074/489f715c-1c82-11e6-8bd4-76d2322cca5d.png)

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon.
