### ISSUE TITLE
The New Frontier Quest - Mission 8 Teleports Bug

### ISSUE THREAD

**Issue by RafaelPereiraa** [gordonbay/capernia-ots-datapack#21]
![sem titulo](https://cloud.githubusercontent.com/assets/1608140/15346982/719b3e68-1c93-11e6-9c7f-45079a8ae8d1.jpg)

The teleports on `33198, 31345, 6,` and `33199, 31345, 6`, are teleportating the characters even if they don't have the mission 8 of the quest completed (or any storages of the quest).

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed on the next update.
