### ISSUE TITLE
"Killing in the Name of... Quest" Wrong Npc

### ISSUE THREAD

**Issue by RafaelPereiraa** [gordonbay/capernia-ots-datapack#22]
![sem titulo2](https://cloud.githubusercontent.com/assets/1608140/15383672/369e1686-1d6b-11e6-9306-ce79ed036631.jpg)
NPC Grizzly Adams are giving the Necromancers task 1 and 2 at the same time, and you should only do the second part after the first one is done.

He (Grizzly Adams) don't even should give this task. These tasks are given by npc Lugri, near Thais. You can see it here: [Wikia Killing in the Name of... Quest/Spoiler, unranked tasks](http://tibia.wikia.com/wiki/Killing_in_the_Name_of..._Quest#Unranked_Tasks)

**Comment by gordonbay** [comment]
NPC Grizzly Adams shouldn't give this task accordingly to your provided link, this is a NPC Lugri Task.

**Comment by gordonbay** [comment]
I will keep Lugri task e remove the same from Grizzly.
