### ISSUE TITLE
[Question] Change the map

### ISSUE THREAD

**Issue by nikko1337** [gordonbay/capernia-ots-datapack#24]
Can you post RME to edit the map or at least tell me what I should do? I can open it just fine using RME for 10.90 and otbm from the datapack but as soon as I save I cannot open it anymore. It says Unsupported Version (8).

Thank you

**Comment by gordonbay** [comment]
[Use this](https://mega.nz/#!z9910YbL!9cHUvoYlrFiwshsVCe-JEKKzqrwp-w7ZsCqhFiAtBWE).
You are probably doing something wrong, you need to import the map and not open it. Need to copy capernia item.otb to rme folder.
Closed as totally off-topic.
