### ISSUE TITLE
The Explorer Society Quest

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#27]
Explorer Society Quest has something wrong:

Following the http://www.tibiawiki.com.br/wiki/The_Explorer_Society_Quest

After I asked to join Explorer NPC Angus my quest should been updated but wasn't. 
![sem titulo](https://cloud.githubusercontent.com/assets/11077805/15592058/1cec450c-2377-11e6-8395-d3f97653d114.png)

Because of that im not able to open this door:
![sem titulo2](https://cloud.githubusercontent.com/assets/11077805/15592067/2f3babd0-2377-11e6-89aa-7ce7220c3560.png)

**Comment by gordonbay** [comment]
I don't know if there is any condition to open this door, the tutorial says nothing, so i ll just leave it unlocked.
Thanks for reporting this bug, it will be fixed soon.

**Comment by gexarthas** [comment]
what about quest log? Do Have any idea? Also I transpass the door and I checked the reward box and is empty

**Comment by gordonbay** [comment]
I ll upload quest log now, its done trough `quests.xml`. I noticed that reward box was empty and fixed it with proper item and storage.

**Comment by gordonbay** [comment]
I just made [this push](https://github.com/gordonbay/capernia-ots-datapack/commit/c2bccba762afa397fecb7041b32d8cf972789297) look at that and you ill understand how do make questlog on next missions. I got no time to debug all missions and looks there is a lot of stuff missing. If you are debugging The Explorer Society Quest you should update quests.xml file.

**Comment by gexarthas** [comment]
Thx I will soon as I i finish i will send a new pull request
