### ISSUE TITLE
Map Changes

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#28]
This places and npcs in downtown Thais are modified and
following the rules about custom content shouldn't exist:

![sem titulo1](https://cloud.githubusercontent.com/assets/11077805/15592290/e36efcdc-2378-11e6-881d-b07532a6c500.jpg)

Same here:
![sem titulo2](https://cloud.githubusercontent.com/assets/11077805/15592291/e45117ac-2378-11e6-8445-118da1cac4d6.jpg)

And here:
![sem titulo3](https://cloud.githubusercontent.com/assets/11077805/15592294/e536cd6a-2378-11e6-9181-68ffd9a5af8d.png)

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon.
