### ISSUE TITLE
Enchantments not working

### ISSUE THREAD

**Issue by Thyrekz** [gordonbay/capernia-ots-datapack#32]
Hello, ive been trying to enchant items such as rainbow shield or even small sapphires or emeralds or whatever, but it didnt let me, so i started searching (because im not a scripter) and i found that to use tables as in your actions/scripts/other/enchanting.lua you need to add the function table.find in your data/global.lua
![untitled](https://cloud.githubusercontent.com/assets/19528918/15632675/e2c06e0e-255f-11e6-9405-412060c9be39.png)

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon.
