### ISSUE TITLE
Reporting Bugs!

### ISSUE THREAD

**Issue by Droox** [gordonbay/capernia-ots-datapack#34]
- Dead Blood Priest - debuging!

- Gates of yalahar needing missions to pass! mechanism.lua in data\actions\scripts\quests\in service of yalahar\

- Acess to the goroma's boat only by luck!

-Acess to Goroma's hunt only by quest!

- Renegade Knight have only 65 of HP e 0 de exp!

- Unrealized Dream Don't work!

Sorry for my english!

**Comment by gordonbay** [comment]
You post don't follow [this rules](https://github.com/gordonbay/capernia-ots-datapack/wiki/Issues) and is too inconspicuous, like what do you mean by Dead Blood Priest debugging, or acess goroma's boat by luck? is there missing any npc or something?

**Comment by gordonbay** [comment]
[Exemple of good post](https://github.com/gordonbay/capernia-ots-datapack/issues/28)

**Comment by M4GO** [comment]
Bug on map inq:
33219, 31622, 9 >> Change eart for floor
Portal no have UID
33358, 31588, 12 
33356, 31589, 11
33365, 31612, 11
Harbour Place 1 (Shop) >> Thais
33677, 31598, 7 >> Krailos Boat and more.

**Comment by gordonbay** [comment]
`*M4GO*` if you want to report bugs make your own thread.

**Comment by gordonbay** [comment]
As there was no reponse i ll close this topic.
