### ISSUE TITLE
its a question, but i didnt know where to ask..

### ISSUE THREAD

**Issue by Thyrekz** [gordonbay/capernia-ots-datapack#35]
Do you know if it is possible to add this new npc Cledwyn? the one who trades items for silver tokens?

**Comment by gordonbay** [comment]
This is a missing feature and right now im focused on fix things, so im going to make a missing feature table at wiki.

**Comment by Thyrekz** [comment]
thats good i was just wondering =) thank you anyway and youre making an exellent jobbbbb
