### ISSUE TITLE
Reporting Bugs

### ISSUE THREAD

**Issue by M4GO** [gordonbay/capernia-ots-datapack#38]
**Bug on map inq:**
33219, 31622, 9 >> Change eart for floor
**Portal no have UID**
33358, 31588, 12
33356, 31589, 11
33365, 31612, 11
Harbour Place 1 (Shop) >> Thais
33677, 31598, 7 >> Krailos Boat and more.

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon. As you dont mention whats wrong with Harbour Place 1 nothing changed. Next time that you post a inconspicuous thred i will just close it.
