### ISSUE TITLE
not removing weapon charges

### ISSUE THREAD

**Issue by Thyrekz** [gordonbay/capernia-ots-datapack#40]
it is not removing weapon charges, i searched a lot and i found nothing so i let you know about it

the following weapon's charges are wrong too
Glooth Axe, Club, Blade
charges from 4 to 2 in ITEMS.XML :
<attribute key="charges" value="2" />

**Comment by gexarthas** [comment]
Hello mate,

Check [this example ](https://github.com/gexarthas/capernia-ots-datapack/blob/gtx/data/weapons/weapons.xml) loot for removecharge on action.

**Comment by Thyrekz** [comment]
Thanks i will try ! :D

**Comment by Thyrekz** [comment]
it worked dude thanks a lot

**Comment by gordonbay** [comment]
Thanks for reporting this bug, it will be fixed soon.
