### ISSUE TITLE
Problem with website

### ISSUE THREAD

**Issue by newacc12** [gordonbay/capernia-ots-datapack#45]
I tried to create a new account using the website on the res folder and I have some errors:

Query: INSERT INTO `accounts` (`name`, `password`, `premdays`, `lastday`, `email`, `key`, `create_ip`, `creation`, `premium_points`, `page_access`, `location`, `rlname`, `email_new`, `email_new_time`, `email_code`, `next_email`, `last_post`, `flag`, `guild_points`) VALUES ('TEST', '7c4a8d09ca3762af61e59520943dc26494f8941b', '3065', '1467773185', 'test@test.com', '', '3483498616', '1467773185', '', '', '', '', '', '', '', '', '', 'ca', '')
SQLSTATE:	HY000
Driver code:	1366
Error message:	Incorrect integer value: '' for column 'premium_points' at row 1

premium_points is integer with the default value of 0 but in this case it's sending ''. Looking at the code I believe it's happening because the code is using the PHP Quote function in which for null values return '' as described here at the very bottom: http://php.net/manual/en/pdo.quote.php. I also believe it will happen for all other fields there are integers. Is this just happening to me? I am using linux Ubuntu and mysql 5.6.28-0ubuntu0.15.04.1 - (Ubuntu)

Thanks.

**Comment by gordonbay** [comment]
I got no error on character creation process and wasn't able to reproduce your problem.

**Comment by newacc12** [comment]
It was on account creation not character. I could not test character yet. Could this be a problem related to linux/php/mysql version or any kind of configuration? It is very weird because that's the exact query that is hitting the database without any changes to any php file except for the config to point to otserv folder.

**Comment by gordonbay** [comment]
Still no errors here, anyway the problem is very clear, the columm 'premium_points' dont accept the data type given by the character ", changin this columm to varchar o something else may solve your problem.

**Comment by newacc12** [comment]
I understand that but I see this as a workaround. It's working for you, it should be working for me too without any changes to the database or source. My guess is that it must be some kind of setting.  Anyway you can close the issue if you want. If I find the solution I can reopen. Thanks!

**Comment by newacc12** [comment]
Ok I found the problem. As I though it was a configuration in mysql. SQL MODE was set to:

sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

I just set it to blank using this: SET GLOBAL sql_mode = '';

Now it's working without any changes to the source code.
