### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by kito2** [gordonbay/capernia-ots-datapack#46]
Could you upload sources in order to be compiled on Linux?

**Comment by gordonbay** [comment]
This is a datapack project, you can download souces on TFS project.

**Comment by kito2** [comment]
I downloaded the sources from TFS 1.2, compiled and tried to run with this datapack and got TONS of errors.... After fixing those errors got the server crashed on loading "script system".

**Comment by gordonbay** [comment]
It will be fixed when TFS release 10.93+ version, untill then you will have to use the provided executables or fix the problems by yourself.
