### ISSUE TITLE
Crusader Helmet Quest

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#7]
There is a bug with spider web inside crusader helmet quest. You suppose to use fire bug or melee weapon to destroy it, but you can't. 

You may replace on items.xml:

`	<item fromid="7538" toid="7543" article="a" name="spider web" />`

to:

`	<item fromid="7538" toid="7543" article="a" name="spider web" />
	<item id="7544" name="the remains of a spider web">
		<attribute key="decayTo" value="7538" />
		<attribute key="duration" value="60" />
	</item>`

It fix for use with fire bug but i couldnt fix for melee weapons.

Regards

Gex

**Comment by gordonbay** [comment]
I was able to replicate the situation and shall release an fix tomorrow, but the only way to make melee weapons cut web is change each one to load same script of firebug because of the limitations of ONUSE() function.

**Comment by gordonbay** [comment]
Its been fixed by todays update, [https://github.com/gordonbay/capernia-ots-datapack/blob/master/CHANGELOG.md#005-11052016](11/05/2016 updates)

**Comment by gexarthas** [comment]
Tested! worked like a charm.

Thx
