### ISSUE TITLE
Map Rotworms Darashia

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#8]
Map is brooken on darashia's rotworm respaw:
![print](https://cloud.githubusercontent.com/assets/11077805/15202147/01c1a470-17ce-11e6-886d-b36bacd83f37.png)

**Comment by gordonbay** [comment]
I have been able to replicate this problem and will fix it tomorrow. Keep reporting problems.

**Comment by gordonbay** [comment]
Its has been fixed by todays update, please test it now.

**Comment by gexarthas** [comment]
Solved!

Thx
