### ISSUE TITLE
NPC Chemar - Error Script

### ISSUE THREAD

**Issue by gexarthas** [gordonbay/capernia-ots-datapack#9]
![print2](https://cloud.githubusercontent.com/assets/11077805/15204341/b6f2c842-17e2-11e6-8361-3bceeff7de4a.jpg)

Every time when you travel from darashia carpet to any destination you got :
![print1](https://cloud.githubusercontent.com/assets/11077805/15204338/aae36b10-17e2-11e6-8493-4d688e3e4d70.jpg)

**Comment by gordonbay** [comment]
Its has been fixed by todays update, please test it now.

**Comment by gexarthas** [comment]
Solved!

Thx
